#############################################################################
# Makefile for building: geom3D
# Generated by qmake (2.01a) (Qt 4.8.7) on: mar. avr. 4 22:42:09 2017
# Project:  geom3D.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile geom3D.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-QGLViewer \
		sub-OGLRender \
		sub-Transfos \
		sub-Revolution \
		sub-Projet_modeling

QGLViewer//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) QGLViewer/ || $(MKDIR) QGLViewer/ 
	cd QGLViewer/ && $(QMAKE) /home/alex/Documents/fac/Geom3D/Geom_3D/QGLViewer/QGLViewer.pro -o $(MAKEFILE)
sub-QGLViewer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) QGLViewer/ || $(MKDIR) QGLViewer/ 
	cd QGLViewer/ && $(QMAKE) /home/alex/Documents/fac/Geom3D/Geom_3D/QGLViewer/QGLViewer.pro -o $(MAKEFILE)
sub-QGLViewer: QGLViewer//$(MAKEFILE) FORCE
	cd QGLViewer/ && $(MAKE) -f $(MAKEFILE)
sub-QGLViewer-make_default: QGLViewer//$(MAKEFILE) FORCE
	cd QGLViewer/ && $(MAKE) -f $(MAKEFILE) 
sub-QGLViewer-make_first: QGLViewer//$(MAKEFILE) FORCE
	cd QGLViewer/ && $(MAKE) -f $(MAKEFILE) first
sub-QGLViewer-all: QGLViewer//$(MAKEFILE) FORCE
	cd QGLViewer/ && $(MAKE) -f $(MAKEFILE) all
sub-QGLViewer-clean: QGLViewer//$(MAKEFILE) FORCE
	cd QGLViewer/ && $(MAKE) -f $(MAKEFILE) clean
sub-QGLViewer-distclean: QGLViewer//$(MAKEFILE) FORCE
	cd QGLViewer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-QGLViewer-install_subtargets: QGLViewer//$(MAKEFILE) FORCE
	cd QGLViewer/ && $(MAKE) -f $(MAKEFILE) install
sub-QGLViewer-uninstall_subtargets: QGLViewer//$(MAKEFILE) FORCE
	cd QGLViewer/ && $(MAKE) -f $(MAKEFILE) uninstall
OGLRender//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) OGLRender/ || $(MKDIR) OGLRender/ 
	cd OGLRender/ && $(QMAKE) /home/alex/Documents/fac/Geom3D/Geom_3D/OGLRender/OGLRender.pro -o $(MAKEFILE)
sub-OGLRender-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) OGLRender/ || $(MKDIR) OGLRender/ 
	cd OGLRender/ && $(QMAKE) /home/alex/Documents/fac/Geom3D/Geom_3D/OGLRender/OGLRender.pro -o $(MAKEFILE)
sub-OGLRender: OGLRender//$(MAKEFILE) FORCE
	cd OGLRender/ && $(MAKE) -f $(MAKEFILE)
sub-OGLRender-make_default: OGLRender//$(MAKEFILE) FORCE
	cd OGLRender/ && $(MAKE) -f $(MAKEFILE) 
sub-OGLRender-make_first: OGLRender//$(MAKEFILE) FORCE
	cd OGLRender/ && $(MAKE) -f $(MAKEFILE) first
sub-OGLRender-all: OGLRender//$(MAKEFILE) FORCE
	cd OGLRender/ && $(MAKE) -f $(MAKEFILE) all
sub-OGLRender-clean: OGLRender//$(MAKEFILE) FORCE
	cd OGLRender/ && $(MAKE) -f $(MAKEFILE) clean
sub-OGLRender-distclean: OGLRender//$(MAKEFILE) FORCE
	cd OGLRender/ && $(MAKE) -f $(MAKEFILE) distclean
sub-OGLRender-install_subtargets: OGLRender//$(MAKEFILE) FORCE
	cd OGLRender/ && $(MAKE) -f $(MAKEFILE) install
sub-OGLRender-uninstall_subtargets: OGLRender//$(MAKEFILE) FORCE
	cd OGLRender/ && $(MAKE) -f $(MAKEFILE) uninstall
Transfos//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Transfos/ || $(MKDIR) Transfos/ 
	cd Transfos/ && $(QMAKE) /home/alex/Documents/fac/Geom3D/Geom_3D/Transfos/Transfos.pro -o $(MAKEFILE)
sub-Transfos-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Transfos/ || $(MKDIR) Transfos/ 
	cd Transfos/ && $(QMAKE) /home/alex/Documents/fac/Geom3D/Geom_3D/Transfos/Transfos.pro -o $(MAKEFILE)
sub-Transfos: Transfos//$(MAKEFILE) sub-QGLViewer \
		sub-OGLRender FORCE
	cd Transfos/ && $(MAKE) -f $(MAKEFILE)
sub-Transfos-make_default: Transfos//$(MAKEFILE) sub-QGLViewer-make_default sub-OGLRender-make_default FORCE
	cd Transfos/ && $(MAKE) -f $(MAKEFILE) 
sub-Transfos-make_first: Transfos//$(MAKEFILE) sub-QGLViewer-make_first sub-OGLRender-make_first FORCE
	cd Transfos/ && $(MAKE) -f $(MAKEFILE) first
sub-Transfos-all: Transfos//$(MAKEFILE) sub-QGLViewer-all sub-OGLRender-all FORCE
	cd Transfos/ && $(MAKE) -f $(MAKEFILE) all
sub-Transfos-clean: Transfos//$(MAKEFILE) sub-QGLViewer-clean sub-OGLRender-clean FORCE
	cd Transfos/ && $(MAKE) -f $(MAKEFILE) clean
sub-Transfos-distclean: Transfos//$(MAKEFILE) sub-QGLViewer-distclean sub-OGLRender-distclean FORCE
	cd Transfos/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Transfos-install_subtargets: Transfos//$(MAKEFILE) sub-QGLViewer-install_subtargets sub-OGLRender-install_subtargets FORCE
	cd Transfos/ && $(MAKE) -f $(MAKEFILE) install
sub-Transfos-uninstall_subtargets: Transfos//$(MAKEFILE) sub-QGLViewer-uninstall_subtargets sub-OGLRender-uninstall_subtargets FORCE
	cd Transfos/ && $(MAKE) -f $(MAKEFILE) uninstall
Revolution//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Revolution/ || $(MKDIR) Revolution/ 
	cd Revolution/ && $(QMAKE) /home/alex/Documents/fac/Geom3D/Geom_3D/Revolution/Revolution.pro -o $(MAKEFILE)
sub-Revolution-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Revolution/ || $(MKDIR) Revolution/ 
	cd Revolution/ && $(QMAKE) /home/alex/Documents/fac/Geom3D/Geom_3D/Revolution/Revolution.pro -o $(MAKEFILE)
sub-Revolution: Revolution//$(MAKEFILE) sub-QGLViewer \
		sub-OGLRender FORCE
	cd Revolution/ && $(MAKE) -f $(MAKEFILE)
sub-Revolution-make_default: Revolution//$(MAKEFILE) sub-QGLViewer-make_default sub-OGLRender-make_default FORCE
	cd Revolution/ && $(MAKE) -f $(MAKEFILE) 
sub-Revolution-make_first: Revolution//$(MAKEFILE) sub-QGLViewer-make_first sub-OGLRender-make_first FORCE
	cd Revolution/ && $(MAKE) -f $(MAKEFILE) first
sub-Revolution-all: Revolution//$(MAKEFILE) sub-QGLViewer-all sub-OGLRender-all FORCE
	cd Revolution/ && $(MAKE) -f $(MAKEFILE) all
sub-Revolution-clean: Revolution//$(MAKEFILE) sub-QGLViewer-clean sub-OGLRender-clean FORCE
	cd Revolution/ && $(MAKE) -f $(MAKEFILE) clean
sub-Revolution-distclean: Revolution//$(MAKEFILE) sub-QGLViewer-distclean sub-OGLRender-distclean FORCE
	cd Revolution/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Revolution-install_subtargets: Revolution//$(MAKEFILE) sub-QGLViewer-install_subtargets sub-OGLRender-install_subtargets FORCE
	cd Revolution/ && $(MAKE) -f $(MAKEFILE) install
sub-Revolution-uninstall_subtargets: Revolution//$(MAKEFILE) sub-QGLViewer-uninstall_subtargets sub-OGLRender-uninstall_subtargets FORCE
	cd Revolution/ && $(MAKE) -f $(MAKEFILE) uninstall
Projet_modeling//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Projet_modeling/ || $(MKDIR) Projet_modeling/ 
	cd Projet_modeling/ && $(QMAKE) /home/alex/Documents/fac/Geom3D/Geom_3D/Projet_modeling/Projet_modeling.pro -o $(MAKEFILE)
sub-Projet_modeling-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Projet_modeling/ || $(MKDIR) Projet_modeling/ 
	cd Projet_modeling/ && $(QMAKE) /home/alex/Documents/fac/Geom3D/Geom_3D/Projet_modeling/Projet_modeling.pro -o $(MAKEFILE)
sub-Projet_modeling: Projet_modeling//$(MAKEFILE) sub-QGLViewer \
		sub-OGLRender FORCE
	cd Projet_modeling/ && $(MAKE) -f $(MAKEFILE)
sub-Projet_modeling-make_default: Projet_modeling//$(MAKEFILE) sub-QGLViewer-make_default sub-OGLRender-make_default FORCE
	cd Projet_modeling/ && $(MAKE) -f $(MAKEFILE) 
sub-Projet_modeling-make_first: Projet_modeling//$(MAKEFILE) sub-QGLViewer-make_first sub-OGLRender-make_first FORCE
	cd Projet_modeling/ && $(MAKE) -f $(MAKEFILE) first
sub-Projet_modeling-all: Projet_modeling//$(MAKEFILE) sub-QGLViewer-all sub-OGLRender-all FORCE
	cd Projet_modeling/ && $(MAKE) -f $(MAKEFILE) all
sub-Projet_modeling-clean: Projet_modeling//$(MAKEFILE) sub-QGLViewer-clean sub-OGLRender-clean FORCE
	cd Projet_modeling/ && $(MAKE) -f $(MAKEFILE) clean
sub-Projet_modeling-distclean: Projet_modeling//$(MAKEFILE) sub-QGLViewer-distclean sub-OGLRender-distclean FORCE
	cd Projet_modeling/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Projet_modeling-install_subtargets: Projet_modeling//$(MAKEFILE) sub-QGLViewer-install_subtargets sub-OGLRender-install_subtargets FORCE
	cd Projet_modeling/ && $(MAKE) -f $(MAKEFILE) install
sub-Projet_modeling-uninstall_subtargets: Projet_modeling//$(MAKEFILE) sub-QGLViewer-uninstall_subtargets sub-OGLRender-uninstall_subtargets FORCE
	cd Projet_modeling/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: geom3D.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile geom3D.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile geom3D.pro

qmake_all: sub-QGLViewer-qmake_all sub-OGLRender-qmake_all sub-Transfos-qmake_all sub-Revolution-qmake_all sub-Projet_modeling-qmake_all FORCE

make_default: sub-QGLViewer-make_default sub-OGLRender-make_default sub-Transfos-make_default sub-Revolution-make_default sub-Projet_modeling-make_default FORCE
make_first: sub-QGLViewer-make_first sub-OGLRender-make_first sub-Transfos-make_first sub-Revolution-make_first sub-Projet_modeling-make_first FORCE
all: sub-QGLViewer-all sub-OGLRender-all sub-Transfos-all sub-Revolution-all sub-Projet_modeling-all FORCE
clean: sub-QGLViewer-clean sub-OGLRender-clean sub-Transfos-clean sub-Revolution-clean sub-Projet_modeling-clean FORCE
distclean: sub-QGLViewer-distclean sub-OGLRender-distclean sub-Transfos-distclean sub-Revolution-distclean sub-Projet_modeling-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-QGLViewer-install_subtargets sub-OGLRender-install_subtargets sub-Transfos-install_subtargets sub-Revolution-install_subtargets sub-Projet_modeling-install_subtargets FORCE
uninstall_subtargets: sub-QGLViewer-uninstall_subtargets sub-OGLRender-uninstall_subtargets sub-Transfos-uninstall_subtargets sub-Revolution-uninstall_subtargets sub-Projet_modeling-uninstall_subtargets FORCE

sub-QGLViewer-check: QGLViewer/$(MAKEFILE)
	cd QGLViewer/ && $(MAKE) -f $(MAKEFILE) check
sub-OGLRender-check: OGLRender/$(MAKEFILE)
	cd OGLRender/ && $(MAKE) -f $(MAKEFILE) check
sub-Transfos-check: Transfos/$(MAKEFILE) sub-QGLViewer-check sub-OGLRender-check
	cd Transfos/ && $(MAKE) -f $(MAKEFILE) check
sub-Revolution-check: Revolution/$(MAKEFILE) sub-QGLViewer-check sub-OGLRender-check
	cd Revolution/ && $(MAKE) -f $(MAKEFILE) check
sub-Projet_modeling-check: Projet_modeling/$(MAKEFILE) sub-QGLViewer-check sub-OGLRender-check
	cd Projet_modeling/ && $(MAKE) -f $(MAKEFILE) check
check: sub-QGLViewer-check sub-OGLRender-check sub-Transfos-check sub-Revolution-check sub-Projet_modeling-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

